### ISSUE TITLE
Point index 33 is out of bounds

### ISSUE THREAD

**Issue by DavidPhillipOster** [WMays287/openscad-toolkit#1]
I just loaded https://github.com/WMays287/openscad-toolkit/blob/main/profile_extrude.scad
 into OpenSCAD as is, and the OpenSCAD 2021.01  console said:

WARNING: Point index 33 is out of bounds (from faces[30][2]) in file profile_extrude.scad, line 63
WARNING: Point index 32 is out of bounds (from faces[30][3]) in file profile_extrude.scad, line 63
WARNING: Point index 34 is out of bounds (from faces[31][2]) in file profile_extrude.scad, line 63
WARNING: Point index 33 is out of bounds (from faces[31][3]) in file profile_extrude.scad, line 63
WARNING: Point index 35 is out of bounds (from faces[32][2]) in file profile_extrude.scad, line 63
WARNING: Point index 34 is out of bounds (from faces[32][3]) in file profile_extrude.scad, line 63
WARNING: Point index 32 is out of bounds (from faces[33][2]) in file profile_extrude.scad, line 63
WARNING: Point index 35 is out of bounds (from faces[33][3]) in file profile_extrude.scad, line 63
WARNING: PolySet has degenerate polygons

**Comment by WMays287** [comment]
Thanks, I don't look at the console that often.
Turns out, there was an error in line 77:
`            for (j = [0 : 1 : len(profile_points) - 1])`
This is responsible for iterating over every slice along the extrusion path, and the problem was that it included the very top edge. There ARE no points up there to be added to the polyhedron because I was accidentally over-scanning, and OpenSCAD apparently didn't think that was worth throwing an error, and instead just gave a warning.
The fix looks like:
`            for (j = [0 : 1 : len(profile_points) - 2])`
That's what was causing the problem, and I'll update the file right away.

**Comment by WMays287** [comment]
The latest version of profile_extrude has been uploaded, which should fix the issue.

**Comment by DavidPhillipOster** [comment]
Confirmed. Thanks
